import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { I18nProvider } from "@/components/I18nProvider";
import { JourneyNav } from "@/components/JourneyNav";
import { MetadataUpdater } from "@/components/MetadataUpdater";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={openSans.variable}>
        <I18nProvider>
          <MetadataUpdater />
          <JourneyNav />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
